# Generated by Django 3.0.3 on 2020-02-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniRecord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=100, null=True)),
                ('recordTime', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
