# Generated by Django 3.0.3 on 2020-03-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_photo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
