# Generated by Django 3.0.3 on 2020-03-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=50)),
            ],
        ),
    ]
