# Generated by Django 3.0.3 on 2020-03-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
