# Generated by Django 3.0.3 on 2020-04-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_zh',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
